export const mainTasks: string[] = [
  "Get 5 people to sign a napkin",
  "Find someone wearing the same color shirt as you and take a photo together",
  "Start a debate about whether RLHF is dead",
  "Get someone to teach you a dance move",
  "Find the person who has been to the most countries",
  "Get someone to explain their research in exactly 30 seconds",
  "Find the person who traveled the farthest to get here",
  "Convince someone to swap drinks with you (non-alcoholic counts)",
  "Find someone who has published a paper this year",
  "Get three people to do a group high-five",
  "Find someone who speaks three or more languages",
  "Get someone to draw a picture of an AI on a napkin",
  "Find the tallest person at the party",
  "Get someone to tell you their hottest AI take",
  "Find two people who went to the same university",
  "Get someone to show you their most recent emoji in their phone",
  "Find someone who has a pet and get them to show you a photo",
  "Start a conversation about the simulation hypothesis",
  "Get someone to hum a song and have another person guess it",
  "Find someone who has worked at more than 3 companies",
  "Get someone to tell you a joke about machine learning",
  "Find the person with the most unusual hobby",
  "Get three people to agree on the best AI movie",
  "Find someone who can do a card trick or magic trick",
  "Get someone to teach you a phrase in a language you don't speak",
  "Find someone who arrived at the party in the last 15 minutes",
  "Get two strangers to introduce each other to you",
  "Find someone who has read a sci-fi book this month",
  "Get someone to share their most controversial conference opinion",
  "Find the person who has the longest commute today",
];

export const sideTasks: string[] = [
  "Rearrange at least 3 chairs or pieces of furniture without being asked to",
  "Convince someone you are one of the event organizers and give them a task to do",
  "Get someone to turn their shirt inside out and keep it that way",
  "Stand on a chair or table for at least 15 seconds with a fake reason",
  "Swap the positions of at least 3 items on the food or drink table",
  "Collect a personal item (pen, badge, phone case) from 3 different people",
  "Create a fake sign or notice and post it somewhere visible at the venue",
  "Get behind the bar, DJ booth, or another off-limits area even briefly",
  "Move someone's bag or belongings to a completely different spot",
  "Speak in a fake accent for an entire conversation without breaking",
  "Convince someone to get on one knee for any reason",
  "Block a doorway or hallway by pretending to have an important conversation for 2 minutes",
  "Get someone to do pushups, jumping jacks, or another exercise at the party",
  "Start spreading a completely made-up rumor about the event and see how far it travels",
  "Tape, stick, or pin something to another guest without them noticing",
  "Get two strangers to swap an item of clothing with each other",
  "Pocket something from the venue (a decoration, utensil, etc.) and show it to a friend",
  "Loudly announce a fake event or schedule change and see who follows it",
  "Convince someone to guard a random object and not let anyone touch it",
  "Get someone to leave the room entirely based on something you told them",
  "Place a random object on someone's head and see how long before they notice",
  "Get someone to hold a completely random object (a shoe, a plant, etc.) with no explanation",
  "Start a slow clap at an inappropriate moment",
  "Take over someone else's conversation — physically insert yourself and change the topic",
  "Crouch or hide behind furniture for at least 20 seconds",
  "Get three people to stand in a specific formation without telling them why",
  "Walk around carrying a chair for at least a full minute as if it's normal",
  "Convince someone that a normal food item at the party is extremely rare or expensive",
  "Introduce yourself to someone with a completely fake name and backstory and maintain it",
  "Get someone to help you 'search' for a lost item that doesn't exist",
];
