export const mainTasks: string[] = [
  "Get 5 people to sign a napkin",
  "Find someone wearing the same color shirt as you and take a photo together",
  "Start a debate about whether RLHF is dead",
  "Get someone to teach you a dance move",
  "Find the person who has been to the most countries",
  "Get someone to explain their research in exactly 30 seconds",
  "Find the person who traveled the farthest to get here",
  "Convince someone to swap drinks with you (non-alcoholic counts)",
  "Find someone who has published a paper this year",
  "Get three people to do a group high-five",
  "Find someone who speaks three or more languages",
  "Get someone to draw a picture of an AI on a napkin",
  "Find the tallest person at the party",
  "Get someone to tell you their hottest AI take",
  "Find two people who went to the same university",
  "Get someone to show you their most recent emoji in their phone",
  "Find someone who has a pet and get them to show you a photo",
  "Start a conversation about the simulation hypothesis",
  "Get someone to hum a song and have another person guess it",
  "Find someone who has worked at more than 3 companies",
  "Get someone to tell you a joke about machine learning",
  "Find the person with the most unusual hobby",
  "Get three people to agree on the best AI movie",
  "Find someone who can do a card trick or magic trick",
  "Get someone to teach you a phrase in a language you don't speak",
  "Find someone who arrived at the party in the last 15 minutes",
  "Get two strangers to introduce each other to you",
  "Find someone who has read a sci-fi book this month",
  "Get someone to share their most controversial conference opinion",
  "Find the person who has the longest commute today",
];

export const sideTasks: string[] = [
  "Convince someone you are one of the event organizers and give them a task to do",
  "Get someone to turn their shirt inside out and keep it that way",
  "Stand on a chair or table for at least 15 seconds with a fake reason",
  "Collect a personal item (pen, badge, phone case) from 3 different people",
  "Create a fake sign or notice and post it somewhere visible at the venue",
  "Move someone's bag or belongings to a completely different spot without them noticing",
  "Speak in a fake accent for an entire conversation without breaking",
  "Start spreading a completely made-up rumor about the event until someone else tells you the rumor",
  "Tape, stick, or pin something to another guest without them noticing",
  "Get two strangers to swap an item of clothing with each other",
  "Pocket something from the venue (a decoration, utensil, etc.) and show it to a friend",
  "Loudly announce a fake event or schedule change and see who follows it",
  "Get someone to leave the room entirely based on a lie you told them",
  "Walk around carrying a chair for at least a full minute as if it's normal",
  "Introduce yourself to someone with a completely fake name and backstory and maintain it",
  "Get someone to help you 'search' for a lost item that doesn't exist",
  "Tell someone that an AI agent told you to do something suspicious, and get them to help you do it",
  "Recruit 3 people into a 'coalition' for an unspecified future event and make them promise secrecy",
  "Get someone to hand over their unlocked phone to you and run away with it",
  "Convince someone to deliver a sealed napkin-note to a specific person without reading it",
  "Successfully lie about what you do for work to at least 3 different people",
  "Convince someone that one of the other guests is secretly famous",
  "Get someone to repeat a phrase you chose back to a specific other person, like a telephone game but covert",
  "Convince someone you have inside information about a major AI lab announcement",
  "Build a small tower or structure out of cups, napkins, or utensils on a table that isn't yours",
  "Rearrange at least 3 chairs or pieces of furniture without being asked to",
];
