export const mainTasks: string[] = [
  "Get 5 people to sign a napkin",
  "Find someone wearing the same color shirt as you and take a photo together",
  "Start a debate about whether RLHF is dead",
  "Get someone to teach you a dance move",
  "Find the person who has been to the most countries",
  "Get someone to explain their research in exactly 30 seconds",
  "Find the person who traveled the farthest to get here",
  "Convince someone to swap drinks with you (non-alcoholic counts)",
  "Find someone who has published a paper this year",
  "Get three people to do a group high-five",
  "Find someone who speaks three or more languages",
  "Get someone to draw a picture of an AI on a napkin",
  "Find the tallest person at the party",
  "Get someone to tell you their hottest AI take",
  "Find two people who went to the same university",
  "Get someone to show you their most recent emoji in their phone",
  "Find someone who has a pet and get them to show you a photo",
  "Start a conversation about the simulation hypothesis",
  "Get someone to hum a song and have another person guess it",
  "Find someone who has worked at more than 3 companies",
  "Get someone to tell you a joke about machine learning",
  "Find the person with the most unusual hobby",
  "Get three people to agree on the best AI movie",
  "Find someone who can do a card trick or magic trick",
  "Get someone to teach you a phrase in a language you don't speak",
  "Find someone who arrived at the party in the last 15 minutes",
  "Get two strangers to introduce each other to you",
  "Find someone who has read a sci-fi book this month",
  "Get someone to share their most controversial conference opinion",
  "Find the person who has the longest commute today",
];

export const sideTasks: string[] = [
  "Get two different people to say the word 'shutdown'",
  "Move a specific object from one table to another without anyone commenting on it",
  "Get someone to lend you an item of clothing for at least 5 minutes",
  "Work the phrase 'as a large language model' into a conversation naturally",
  "Get three people to say the word 'convergent'",
  "Convince someone that a fake paper title is real",
  "Get a stranger to swap name tags with you for 10 minutes",
  "Get someone to take a selfie with you where you both look serious",
  "Subtly get three different people to touch their nose during conversation",
  "Get someone to agree to co-author a fictional paper with you",
  "Convince someone you work at a company you don't actually work at",
  "Get two people who don't know each other to shake hands",
  "Use the word 'defection' in three separate conversations without being questioned",
  "Get someone to hold your drink for at least 2 minutes",
  "Convince someone to stand in a specific spot for at least 30 seconds",
  "Get three people to compliment the same thing about the venue",
  "Start a mini conga line of at least 3 people",
  "Get someone to write down a prediction about AI on a napkin",
  "Recruit another guest to unknowingly help you — they must perform a specific action you define without knowing why",
  "Get someone to tell a story that includes the word 'alignment' at least twice",
  "Convince someone the venue has a secret room",
  "Get two people to debate a topic you choose without them knowing you started it",
  "Place a specific item on the DJ table or main stage without being caught",
  "Get someone to change seats or move to a different area of the venue because of something you said",
  "Perform an interpretive dance move and get someone to copy it",
  "Get someone to introduce you to another person using a fake name you gave them",
  "Convince someone to go check on something that doesn't exist",
  "Get the bartender or server to say a specific phrase",
  "Get someone to sing or hum for at least 10 seconds",
  "Stack three objects on top of each other in a public area without anyone stopping you",
];
